version: '2'
services:
  malmo1:
    image: malmo:latest
    expose:
      - "10000"
  malmo2:
      image: malmo:latest
      expose:
        - "10000"
  agents:
      image: my_exp:latest
      volumes: ../../ai_challenge/tasks/pig_chase/scripts:/root/malmo-challenge/ai_challenge/tasks/pig_chase/scripts
      working_dir: /root/malmo-challenge/ai_challenge/tasks/pig_chase/scripts
      command: bash -c "python evaluate_trained_agent.py malmo1:10000 malmo2:10000 -c eval_config.txt
      ports:
        - "6006:6006"
      links:
        - malmo1
        - malmo2